// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.3
// source: app-runtime.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppRuntime_Reconcile_FullMethodName = "/station.runtime.v1.AppRuntime/Reconcile"
)

// AppRuntimeClient is the client API for AppRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal only. Core supplies authenticated ownership, never browser input directly.
type AppRuntimeClient interface {
	// Reconcile advances one durable operation and returns observed execution facts.
	// Retrying the identical operation_id is safe after a lost response.
	Reconcile(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppProgress, error)
}

type appRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewAppRuntimeClient(cc grpc.ClientConnInterface) AppRuntimeClient {
	return &appRuntimeClient{cc}
}

func (c *appRuntimeClient) Reconcile(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppProgress, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppProgress)
	err := c.cc.Invoke(ctx, AppRuntime_Reconcile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppRuntimeServer is the server API for AppRuntime service.
// All implementations must embed UnimplementedAppRuntimeServer
// for forward compatibility.
//
// Internal only. Core supplies authenticated ownership, never browser input directly.
type AppRuntimeServer interface {
	// Reconcile advances one durable operation and returns observed execution facts.
	// Retrying the identical operation_id is safe after a lost response.
	Reconcile(context.Context, *AppRequest) (*AppProgress, error)
	mustEmbedUnimplementedAppRuntimeServer()
}

// UnimplementedAppRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppRuntimeServer struct{}

func (UnimplementedAppRuntimeServer) Reconcile(context.Context, *AppRequest) (*AppProgress, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconcile not implemented")
}
func (UnimplementedAppRuntimeServer) mustEmbedUnimplementedAppRuntimeServer() {}
func (UnimplementedAppRuntimeServer) testEmbeddedByValue()                    {}

// UnsafeAppRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppRuntimeServer will
// result in compilation errors.
type UnsafeAppRuntimeServer interface {
	mustEmbedUnimplementedAppRuntimeServer()
}

func RegisterAppRuntimeServer(s grpc.ServiceRegistrar, srv AppRuntimeServer) {
	// If the following call panics, it indicates UnimplementedAppRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppRuntime_ServiceDesc, srv)
}

func _AppRuntime_Reconcile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppRuntimeServer).Reconcile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppRuntime_Reconcile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppRuntimeServer).Reconcile(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppRuntime_ServiceDesc is the grpc.ServiceDesc for AppRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "station.runtime.v1.AppRuntime",
	HandlerType: (*AppRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reconcile",
			Handler:    _AppRuntime_Reconcile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app-runtime.proto",
}
