// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: app-runtime.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OperationId         string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	RequestId           string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId              string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganizationId      string                 `protobuf:"bytes,4,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	StationId           string                 `protobuf:"bytes,5,opt,name=station_id,json=stationId,proto3" json:"station_id,omitempty"`
	AppId               string                 `protobuf:"bytes,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppVersion          string                 `protobuf:"bytes,7,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Action              string                 `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	ExpectedWorkloadUid string                 `protobuf:"bytes,9,opt,name=expected_workload_uid,json=expectedWorkloadUid,proto3" json:"expected_workload_uid,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AppRequest) Reset() {
	*x = AppRequest{}
	mi := &file_app_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppRequest) ProtoMessage() {}

func (x *AppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppRequest.ProtoReflect.Descriptor instead.
func (*AppRequest) Descriptor() ([]byte, []int) {
	return file_app_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *AppRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *AppRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AppRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AppRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AppRequest) GetStationId() string {
	if x != nil {
		return x.StationId
	}
	return ""
}

func (x *AppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *AppRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AppRequest) GetExpectedWorkloadUid() string {
	if x != nil {
		return x.ExpectedWorkloadUid
	}
	return ""
}

type AppProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OperationId     string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Status          string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Phase           string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	DownloadedBytes int64                  `protobuf:"varint,4,opt,name=downloaded_bytes,json=downloadedBytes,proto3" json:"downloaded_bytes,omitempty"`
	TotalBytes      *int64                 `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3,oneof" json:"total_bytes,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppProgress) Reset() {
	*x = AppProgress{}
	mi := &file_app_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppProgress) ProtoMessage() {}

func (x *AppProgress) ProtoReflect() protoreflect.Message {
	mi := &file_app_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppProgress.ProtoReflect.Descriptor instead.
func (*AppProgress) Descriptor() ([]byte, []int) {
	return file_app_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *AppProgress) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *AppProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AppProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *AppProgress) GetDownloadedBytes() int64 {
	if x != nil {
		return x.DownloadedBytes
	}
	return 0
}

func (x *AppProgress) GetTotalBytes() int64 {
	if x != nil && x.TotalBytes != nil {
		return *x.TotalBytes
	}
	return 0
}

func (x *AppProgress) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AppProgress) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_app_runtime_proto protoreflect.FileDescriptor

const file_app_runtime_proto_rawDesc = "" +
	"\n" +
	"\x11app-runtime.proto\x12\x12station.runtime.v1\"\xb3\x02\n" +
	"\n" +
	"AppRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12'\n" +
	"\x0forganization_id\x18\x04 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"station_id\x18\x05 \x01(\tR\tstationId\x12\x15\n" +
	"\x06app_id\x18\x06 \x01(\tR\x05appId\x12\x1f\n" +
	"\vapp_version\x18\a \x01(\tR\n" +
	"appVersion\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action\x122\n" +
	"\x15expected_workload_uid\x18\t \x01(\tR\x13expectedWorkloadUid\"\x83\x02\n" +
	"\vAppProgress\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12)\n" +
	"\x10downloaded_bytes\x18\x04 \x01(\x03R\x0fdownloadedBytes\x12$\n" +
	"\vtotal_bytes\x18\x05 \x01(\x03H\x00R\n" +
	"totalBytes\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessageB\x0e\n" +
	"\f_total_bytes2Z\n" +
	"\n" +
	"AppRuntime\x12L\n" +
	"\tReconcile\x12\x1e.station.runtime.v1.AppRequest\x1a\x1f.station.runtime.v1.AppProgressBQZOgithub.com/verdantflarehub/verdantflare-station-runtime/api/runtimev1;runtimev1b\x06proto3"

var (
	file_app_runtime_proto_rawDescOnce sync.Once
	file_app_runtime_proto_rawDescData []byte
)

func file_app_runtime_proto_rawDescGZIP() []byte {
	file_app_runtime_proto_rawDescOnce.Do(func() {
		file_app_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_runtime_proto_rawDesc), len(file_app_runtime_proto_rawDesc)))
	})
	return file_app_runtime_proto_rawDescData
}

var file_app_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_runtime_proto_goTypes = []any{
	(*AppRequest)(nil),  // 0: station.runtime.v1.AppRequest
	(*AppProgress)(nil), // 1: station.runtime.v1.AppProgress
}
var file_app_runtime_proto_depIdxs = []int32{
	0, // 0: station.runtime.v1.AppRuntime.Reconcile:input_type -> station.runtime.v1.AppRequest
	1, // 1: station.runtime.v1.AppRuntime.Reconcile:output_type -> station.runtime.v1.AppProgress
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_runtime_proto_init() }
func file_app_runtime_proto_init() {
	if File_app_runtime_proto != nil {
		return
	}
	file_app_runtime_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_runtime_proto_rawDesc), len(file_app_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_runtime_proto_goTypes,
		DependencyIndexes: file_app_runtime_proto_depIdxs,
		MessageInfos:      file_app_runtime_proto_msgTypes,
	}.Build()
	File_app_runtime_proto = out.File
	file_app_runtime_proto_goTypes = nil
	file_app_runtime_proto_depIdxs = nil
}
