apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: verdantflare-station
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: verdantflare
    app.kubernetes.io/component: host-telemetry
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: node-exporter
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: verdantflare-station
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/part-of: verdantflare
    app.kubernetes.io/component: host-telemetry
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-exporter
        app.kubernetes.io/part-of: verdantflare
        app.kubernetes.io/component: host-telemetry
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
        - operator: Exists
      containers:
        - name: node-exporter
          image: registry.cn-qingdao.aliyuncs.com/wod/prometheus:node-exporter-v1.8.1-amd64
          imagePullPolicy: IfNotPresent
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.rootfs=/rootfs
            - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
          ports:
            - name: metrics
              containerPort: 9100
          resources:
            limits:
              cpu: 250m
              memory: 180Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: root
              mountPath: /rootfs
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
