apiVersion: v1
kind: Service
metadata:
  name: {{ include "station-runtime.fullname" . }}
  labels:
    {{- include "station-runtime.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "station-runtime.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
    - name: probe
      port: {{ .Values.service.probePort }}
      targetPort: probe
